[package]
name = "bfield"
version = "0.1.1"
authors = ["Roderick Bovee <roderick@onecodex.com>"]

[dependencies]
bincode = "0.9.2"
mmap-bitvec = { git="ssh://git@github.com/onecodex/mmap-bitvec.git", tag="v0.1.1" }
murmurhash3 = "0.0.5"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = { version = "1.0.4", optional = true}

[features]
marker_lookup = []
legacy = ["mmap-bitvec/backward_bytes", "serde_json"]
wide_markers = ["mmap-bitvec/u128"]
