[package]
name = "bfield"
version = "0.2.1"
authors = ["Roderick Bovee <roderick@onecodex.com>"]
edition = "2018"

[dependencies]
bincode = "1"
mmap-bitvec = { git="ssh://git@github.com/onecodex/mmap-bitvec.git", tag="v0.3.1" }
murmurhash3 = "0.0.5"
serde = "1.0.15"
serde_derive = "1.0.15"

[features]
prefetching = []
